// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using server.Models;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(LogisticsContext))]
    [Migration("20250827192729_homepush2")]
    partial class homepush2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("server.Models.History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("AkkArrived")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("BillCollected")
                        .HasColumnType("date");

                    b.Property<string>("BillNo")
                        .HasColumnType("longtext");

                    b.Property<string>("ContainerType")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("DjbArrived")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DjbDeparted")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DocCollected")
                        .HasColumnType("date");

                    b.Property<string>("DocOwner")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("DocSentDjb")
                        .HasColumnType("date");

                    b.Property<int>("EmpityContainersLeftUnreturned")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Etadjb")
                        .HasColumnType("date");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("longtext");

                    b.Property<int>("LoadedOnfcl")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("LoadingDate")
                        .HasColumnType("date");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("SdtArrived")
                        .HasColumnType("date");

                    b.Property<string>("Shipper")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("TaxPaid")
                        .HasColumnType("date");

                    b.Property<string>("Transitor")
                        .HasColumnType("longtext");

                    b.Property<string>("Uom")
                        .HasColumnType("longtext");

                    b.Property<string>("truckWayBill")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Histories");
                });

            modelBuilder.Entity("server.Models.IntransitFollowup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactPerson")
                        .HasColumnType("longtext");

                    b.Property<string>("Grn")
                        .HasColumnType("longtext");

                    b.Property<string>("Origin")
                        .HasColumnType("longtext");

                    b.Property<string>("PurchaseCompany")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<string>("PurchaseOrder")
                        .HasColumnType("longtext");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("TotalAmountPaid")
                        .HasColumnType("decimal(25,3)");

                    b.Property<decimal?>("TotalAmountRemaning")
                        .HasColumnType("decimal(25,3)");

                    b.Property<decimal?>("TotalPaidInPercent")
                        .HasColumnType("decimal(25,3)");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(25,3)");

                    b.Property<decimal?>("TotalRemaningInPercent")
                        .HasColumnType("decimal(25,3)");

                    b.Property<string>("TransactionId")
                        .HasColumnType("longtext");

                    b.Property<int?>("status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("IntransitFollowups");
                });

            modelBuilder.Entity("server.Models.IntransitItemsDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("LoadedQnty")
                        .HasColumnType("decimal(25,3)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(25,3)");

                    b.Property<decimal>("RemaningQnty")
                        .HasColumnType("decimal(25,3)");

                    b.Property<string>("TransactionId")
                        .HasColumnType("longtext");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(25,3)");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("IntransitItemsDetails");
                });

            modelBuilder.Entity("server.Models.LogisticsFollowup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("AkkArrived")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("BillCollected")
                        .HasColumnType("date");

                    b.Property<string>("BillNo")
                        .HasColumnType("longtext");

                    b.Property<string>("ContainerType")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("DjbArrived")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DjbDeparted")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DocCollected")
                        .HasColumnType("date");

                    b.Property<string>("DocOwner")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("DocSentDjb")
                        .HasColumnType("date");

                    b.Property<int?>("EmpityContainersLeftUnreturned")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Etadjb")
                        .HasColumnType("date");

                    b.Property<int?>("LoadedOnfcl")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("LoadingDate")
                        .HasColumnType("date");

                    b.Property<string>("Origin")
                        .HasColumnType("longtext");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("SdtArrived")
                        .HasColumnType("date");

                    b.Property<string>("Shipper")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("TaxPaid")
                        .HasColumnType("date");

                    b.Property<string>("TransactionId")
                        .HasColumnType("longtext");

                    b.Property<string>("Transitor")
                        .HasColumnType("longtext");

                    b.Property<string>("status")
                        .HasColumnType("longtext");

                    b.Property<string>("truckWayBill")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("LogisticsFollowups");
                });

            modelBuilder.Entity("server.Models.PaymentHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountPaidFrom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(25,3)");

                    b.Property<string>("PaidBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("PaidDate")
                        .HasColumnType("date");

                    b.Property<string>("TransactionId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PaymentHistories");
                });

            modelBuilder.Entity("server.Models.RecycleBin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("AkkArrived")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("BillCollected")
                        .HasColumnType("date");

                    b.Property<string>("BillNo")
                        .HasColumnType("longtext");

                    b.Property<string>("ContainerType")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("DjbArrived")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DjbDeparted")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DocCollected")
                        .HasColumnType("date");

                    b.Property<string>("DocOwner")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("DocSentDjb")
                        .HasColumnType("date");

                    b.Property<int>("EmpityContainersLeftUnreturned")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Etadjb")
                        .HasColumnType("date");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("longtext");

                    b.Property<int>("LoadedOnfcl")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("LoadingDate")
                        .HasColumnType("date");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("SdtArrived")
                        .HasColumnType("date");

                    b.Property<string>("Shipper")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("TaxPaid")
                        .HasColumnType("date");

                    b.Property<string>("Transitor")
                        .HasColumnType("longtext");

                    b.Property<string>("Uom")
                        .HasColumnType("longtext");

                    b.Property<string>("truckWayBill")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("RecycleBins");
                });

            modelBuilder.Entity("server.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("AkkArrived")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("BillCollected")
                        .HasColumnType("date");

                    b.Property<string>("BillNo")
                        .HasColumnType("longtext");

                    b.Property<string>("ContainerType")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("DjbArrived")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DjbDeparted")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DocCollected")
                        .HasColumnType("date");

                    b.Property<string>("DocOwner")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("DocSentDjb")
                        .HasColumnType("date");

                    b.Property<int>("EmpityContainersLeftUnreturned")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Etadjb")
                        .HasColumnType("date");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("longtext");

                    b.Property<int>("LoadedOnfcl")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("LoadingDate")
                        .HasColumnType("date");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("SdtArrived")
                        .HasColumnType("date");

                    b.Property<string>("Shipper")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("TaxPaid")
                        .HasColumnType("date");

                    b.Property<string>("Transitor")
                        .HasColumnType("longtext");

                    b.Property<string>("Uom")
                        .HasColumnType("longtext");

                    b.Property<string>("truckWayBill")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .HasColumnType("longtext");

                    b.Property<string>("Fullname")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Registerd_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Role")
                        .HasColumnType("longtext");

                    b.Property<string>("User_id")
                        .HasColumnType("longtext");

                    b.Property<string>("User_name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("server.Models.UserLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("longtext");

                    b.Property<string>("Action_time")
                        .HasColumnType("longtext");

                    b.Property<string>("Fullname")
                        .HasColumnType("longtext");

                    b.Property<string>("User_id")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UserLogs");
                });

            modelBuilder.Entity("server.Models.logisticsItemsDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<string>("IntransitId")
                        .HasColumnType("longtext");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("LoadedQnty")
                        .HasColumnType("decimal(25,3)");

                    b.Property<decimal?>("RemaningQnty")
                        .HasColumnType("decimal(25,3)");

                    b.Property<decimal?>("TotalQnty")
                        .HasColumnType("decimal(25,3)");

                    b.Property<string>("TransactionId")
                        .HasColumnType("longtext");

                    b.Property<string>("Uom")
                        .HasColumnType("longtext");

                    b.Property<int?>("status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("logisticsItemsDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
