// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using server.Models;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(LogisticsContext))]
    [Migration("20250813124421_RemoveIsDeletedFromRecycleBin")]
    partial class RemoveIsDeletedFromRecycleBin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("server.Models.History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AkkArrived")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("BillNo")
                        .HasColumnType("longtext");

                    b.Property<bool>("ContReturned")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DjbArrived")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DjbDeparted")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LoadingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("SdtArrived")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Shipper")
                        .HasColumnType("longtext");

                    b.Property<string>("Transitor")
                        .HasColumnType("longtext");

                    b.Property<string>("Uom")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Histories");
                });

            modelBuilder.Entity("server.Models.LogisticsFollowup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AkkArrived")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("BillNo")
                        .HasColumnType("longtext");

                    b.Property<bool>("ContReturned")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DjbArrived")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DjbDeparted")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LoadingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("SdtArrived")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Shipper")
                        .HasColumnType("longtext");

                    b.Property<string>("Transitor")
                        .HasColumnType("longtext");

                    b.Property<string>("Uom")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("LogisticsFollowups");
                });

            modelBuilder.Entity("server.Models.RecycleBin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AkkArrived")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("BillNo")
                        .HasColumnType("longtext");

                    b.Property<bool>("ContReturned")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DjbArrived")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DjbDeparted")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LoadingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("SdtArrived")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Shipper")
                        .HasColumnType("longtext");

                    b.Property<string>("Transitor")
                        .HasColumnType("longtext");

                    b.Property<string>("Uom")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("RecycleBins");
                });

            modelBuilder.Entity("server.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AkkArrived")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("BillNo")
                        .HasColumnType("longtext");

                    b.Property<bool>("ContReturned")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DjbArrived")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DjbDeparted")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LoadingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("SdtArrived")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Shipper")
                        .HasColumnType("longtext");

                    b.Property<string>("Transitor")
                        .HasColumnType("longtext");

                    b.Property<string>("Uom")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .HasColumnType("longtext");

                    b.Property<string>("Fullname")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Registerd_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Role")
                        .HasColumnType("longtext");

                    b.Property<string>("User_id")
                        .HasColumnType("longtext");

                    b.Property<string>("User_name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("server.Models.UserLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("longtext");

                    b.Property<string>("Action_time")
                        .HasColumnType("longtext");

                    b.Property<string>("Fullname")
                        .HasColumnType("longtext");

                    b.Property<string>("User_id")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UserLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
